/**
 * Stream API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@bunny.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class ChapterModel {
    /**
    * The title of the chapter
    */
    'title': string;
    /**
    * The start time of the chapter in seconds
    */
    'start'?: number;
    /**
    * The end time of the chapter in seconds
    */
    'end'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "end",
            "baseName": "end",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return ChapterModel.attributeTypeMap;
    }

    public constructor() {
    }
}

