/**
 * Stream API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@bunny.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class CollectionModel {
    /**
    * The video library ID that contains the collection
    */
    'videoLibraryId'?: number;
    /**
    * The unique ID of the collection
    */
    'guid'?: string | null;
    /**
    * The name of the collection
    */
    'name'?: string | null;
    /**
    * The number of videos that the collection contains
    */
    'videoCount'?: number;
    /**
    * The total storage size of the collection
    */
    'totalSize'?: number;
    /**
    * The IDs of videos to be used as preview icons
    */
    'previewVideoIds'?: string | null;
    /**
    * The URLs of preview images of videos in the collection
    */
    'previewImageUrls'?: Array<string> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "videoLibraryId",
            "baseName": "videoLibraryId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "guid",
            "baseName": "guid",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "videoCount",
            "baseName": "videoCount",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "totalSize",
            "baseName": "totalSize",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "previewVideoIds",
            "baseName": "previewVideoIds",
            "type": "string",
            "format": ""
        },
        {
            "name": "previewImageUrls",
            "baseName": "previewImageUrls",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CollectionModel.attributeTypeMap;
    }

    public constructor() {
    }
}

