/**
 * Stream API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@bunny.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VideoModel } from '../models/VideoModel.ts';
import { HttpFile } from '../http/http.ts';

export class PaginationListOfVideoModel {
    /**
    * The total number of items that can be returned
    */
    'totalItems'?: number;
    /**
    * The current page of the response
    */
    'currentPage'?: number;
    /**
    * The number of items returned per page
    */
    'itemsPerPage'?: number;
    /**
    * The result items on the current result
    */
    'items'?: Array<VideoModel> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "totalItems",
            "baseName": "totalItems",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "currentPage",
            "baseName": "currentPage",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "itemsPerPage",
            "baseName": "itemsPerPage",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<VideoModel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PaginationListOfVideoModel.attributeTypeMap;
    }

    public constructor() {
    }
}

