/**
 * Stream API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@bunny.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IssueCodes } from '../models/IssueCodes.ts';
import { Severity } from '../models/Severity.ts';
import { HttpFile } from '../http/http.ts';

export class TranscodingMessageModel {
    'timeStamp'?: Date;
    'level'?: Severity;
    'issueCode'?: IssueCodes;
    'message'?: string | null;
    'value'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "timeStamp",
            "baseName": "timeStamp",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "Severity",
            "format": ""
        },
        {
            "name": "issueCode",
            "baseName": "issueCode",
            "type": "IssueCodes",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TranscodingMessageModel.attributeTypeMap;
    }

    public constructor() {
    }
}



