/**
 * Stream API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@bunny.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChapterModel } from '../models/ChapterModel.ts';
import { MetaTagModel } from '../models/MetaTagModel.ts';
import { MomentModel } from '../models/MomentModel.ts';
import { UpdateVideoModel } from '../models/UpdateVideoModel.ts';
import { HttpFile } from '../http/http.ts';

export class VideoUpdateVideoRequest {
    /**
    * The title of the video
    */
    'title'?: string | null;
    /**
    * The ID of the collection where the video belongs
    */
    'collectionId'?: string | null;
    /**
    * The list of chapters available for the video
    */
    'chapters'?: Array<ChapterModel> | null;
    /**
    * The list of moments available for the video
    */
    'moments'?: Array<MomentModel> | null;
    /**
    * The meta tags added to the video
    */
    'metaTags'?: Array<MetaTagModel> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "collectionId",
            "baseName": "collectionId",
            "type": "string",
            "format": ""
        },
        {
            "name": "chapters",
            "baseName": "chapters",
            "type": "Array<ChapterModel>",
            "format": ""
        },
        {
            "name": "moments",
            "baseName": "moments",
            "type": "Array<MomentModel>",
            "format": ""
        },
        {
            "name": "metaTags",
            "baseName": "metaTags",
            "type": "Array<MetaTagModel>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VideoUpdateVideoRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

