/**
 * Stream API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@bunny.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class VideoHeatmapModel {
    /**
    * The heatmap of the video. 100 is the highest percentage of watch time.
    */
    'heatmap'?: { [key: string]: number; } | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "heatmap",
            "baseName": "heatmap",
            "type": "{ [key: string]: number; }",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return VideoHeatmapModel.attributeTypeMap;
    }

    public constructor() {
    }
}

