/**
 * Stream API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@bunny.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CreateVideoModel } from '../models/CreateVideoModel.ts';
import { HttpFile } from '../http/http.ts';

export class VideoCreateVideoRequest {
    /**
    * The title of the video
    */
    'title': string;
    /**
    * The ID of the collection where the video will be put
    */
    'collectionId'?: string | null;
    /**
    * Video time in ms to extract the main video thumbnail.
    */
    'thumbnailTime'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "collectionId",
            "baseName": "collectionId",
            "type": "string",
            "format": ""
        },
        {
            "name": "thumbnailTime",
            "baseName": "thumbnailTime",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return VideoCreateVideoRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

