/**
 * Stream API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@bunny.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class VideoStatisticsModel {
    /**
    * The constructed chart of checked requests threats
    */
    'viewsChart'?: { [key: string]: number; } | null;
    /**
    * The constructed chart of the total watch time
    */
    'watchTimeChart'?: { [key: string]: number; } | null;
    /**
    * The country view count constructed chart
    */
    'countryViewCounts'?: { [key: string]: number; } | null;
    /**
    * The country watch time constructed chart
    */
    'countryWatchTime'?: { [key: string]: number; } | null;
    'engagementScore'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "viewsChart",
            "baseName": "viewsChart",
            "type": "{ [key: string]: number; }",
            "format": "int64"
        },
        {
            "name": "watchTimeChart",
            "baseName": "watchTimeChart",
            "type": "{ [key: string]: number; }",
            "format": "int64"
        },
        {
            "name": "countryViewCounts",
            "baseName": "countryViewCounts",
            "type": "{ [key: string]: number; }",
            "format": "int64"
        },
        {
            "name": "countryWatchTime",
            "baseName": "countryWatchTime",
            "type": "{ [key: string]: number; }",
            "format": "int64"
        },
        {
            "name": "engagementScore",
            "baseName": "engagementScore",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return VideoStatisticsModel.attributeTypeMap;
    }

    public constructor() {
    }
}

